### ISSUE TITLE
Can't start LokIM frontend - missing file

### ISSUE THREAD

**Issue by michaelKurowski** [Jordan141/LokimFrontend#7]
**Description**
I'm unable to run the LokIM frontend.

**Version**
Commit hash: d56126c6ee3575c0950cb75ff9db19b7b335ec81 (latest on master)

**Steps to reproduce:**
1. `npm i`
2. `npm start`

**Expected result:**
I should be able to see app up and running.

**Actual result:**
Application throws an error

**Screenshoots:**
![image](https://user-images.githubusercontent.com/2772942/38460246-42df9144-3ab6-11e8-92db-9f85c28ce3d4.png)

**Comment by Jordan141** [comment]
Uploaded missing files
